cmt

diff --git a/.pipelines/diabetes_regression-ci.yml b/.pipelines/diabetes_regression-ci.yml
--- a/.pipelines/diabetes_regression-ci.yml
+++ b/.pipelines/diabetes_regression-ci.yml
@@ -2,161 +2,159 @@
 
 resources:
   containers:
-  - container: mlops
-    image: mcr.microsoft.com/mlops/python:latest
+    - container: mlops
+      image: mcr.microsoft.com/mlops/python:latest
 
 pr: none
 trigger:
   branches:
     include:
-    - master
+      - master
   paths:
     include:
-    - diabetes_regression/
-    - ml_service/pipelines/diabetes_regression_build_train_pipeline.py
-    - ml_service/pipelines/diabetes_regression_build_train_pipeline_with_r.py
-    - ml_service/pipelines/diabetes_regression_build_train_pipeline_with_r_on_dbricks.py
+      - diabetes_regression/
+      - ml_service/pipelines/diabetes_regression_build_train_pipeline.py
+      - ml_service/pipelines/diabetes_regression_build_train_pipeline_with_r.py
+      - ml_service/pipelines/diabetes_regression_build_train_pipeline_with_r_on_dbricks.py
 
 variables:
-- template: diabetes_regression-variables-template.yml
-- group: devopsforai-aml-vg
+  - template: diabetes_regression-variables-template.yml
+  - group: devopsforai-aml-vg
 
 pool:
   vmImage: ubuntu-latest
 
 stages:
-- stage: 'Model_CI'
-  displayName: 'Model CI'
-  jobs:
+  - stage: "Model_CI"
+    displayName: "Model CI"
+    jobs:
+      # Job 1 - Azure Login (NO CONTAINER)
+      - job: Azure_Login
+        displayName: "Azure Login & Setup"
+        steps:
+          - task: AzureCLI@2
+            inputs:
+              azureSubscription: "$(WORKSPACE_SVC_CONNECTION)"
+              scriptType: bash
+              scriptLocation: inlineScript
+              inlineScript: |
+                echo "Logged in account:"
+                az account show
+                echo "All available subscriptions:"
+                az account list --output table
 
-  # Job 1 - Azure Login (NO CONTAINER)
-  - job: Azure_Login
-    displayName: "Azure Login & Setup"
-    steps:
-    - task: AzureCLI@2
-      inputs:
-        azureSubscription: '$(WORKSPACE_SVC_CONNECTION)'
-        scriptType: bash
-        scriptLocation: inlineScript
-        inlineScript: |
-          echo "Logged in account:"
-          az account show
-          echo "All available subscriptions:"
-          az account list --output table
+          - task: AzureCLI@2
+            inputs:
+              azureSubscription: "$(WORKSPACE_SVC_CONNECTION)"
+              scriptType: "bash"
+              scriptLocation: "inlineScript"
+              inlineScript: |
+                set -e
+                az version
+                az account show
+            displayName: "Azure Login"
 
-    - task: AzureCLI@2
-      inputs:
-        azureSubscription: '$(WORKSPACE_SVC_CONNECTION)'
-        scriptType: 'bash'
-        scriptLocation: 'inlineScript'
-        inlineScript: |
-          set -e
-          az version
-          az account show
-      displayName: 'Azure Login'
+      # Job 2 - Run inside container
+      - job: Model_CI_Pipeline
+        dependsOn: Azure_Login
+        displayName: "Model CI Pipeline"
+        container: mlops
+        steps:
+          - template: code-quality-template.yml
+          - script: |
+              python -m ml_service.pipelines.diabetes_regression_build_train_pipeline
+            workingDirectory: $(Build.SourcesDirectory)
+            displayName: "Run ML Build Pipeline"
 
-  # Job 2 - Run inside container
-  - job: Model_CI_Pipeline
-    dependsOn: Azure_Login
-    displayName: "Model CI Pipeline"
-    container: mlops
-    steps:
-    - template: code-quality-template.yml
-    - script: |
-        python -m ml_service.pipelines.diabetes_regression_build_train_pipeline
-      workingDirectory: $(Build.SourcesDirectory)
-      displayName: "Run ML Build Pipeline"
-
-- stage: 'Trigger_AML_Pipeline'
-  displayName: 'Train and evaluate model'
-  condition: succeeded()
-  variables:
-    BUILD_URI: '$(SYSTEM.COLLECTIONURI)$(SYSTEM.TEAMPROJECT)/_build/results?buildId=$(BUILD.BUILDID)'
-  jobs:
-  - job: "Get_Pipeline_ID"
-    condition: and(succeeded(), eq(coalesce(variables['auto-trigger-training'], 'true'), 'true'))
-    displayName: "Get Pipeline ID for execution"
-    timeoutInMinutes: 0
-    steps:
-    - task: UsePythonVersion@0
-      inputs:
-        versionSpec: '3.9'
-        addToPath: true
-
-    - task: AzureCLI@2
-      inputs:
-        azureSubscription: '$(WORKSPACE_SVC_CONNECTION)'
-        scriptType: 'bash'
-        scriptLocation: inlineScript
-        workingDirectory: $(Build.SourcesDirectory)
-        inlineScript: |
-          set -e # fail on error
-          python -m pip install --upgrade pip
-          pip install azureml-sdk
-          pip install dotenv
-          export SUBSCRIPTION_ID=$(az account show --query id -o tsv)
-          python -m ml_service.pipelines.run_train_pipeline --output_pipeline_id_file "pipeline_id.txt" --skip_train_execution
-          # Set AMLPIPELINEID variable for next AML Pipeline task in next job
-          AMLPIPELINEID="$(cat pipeline_id.txt)"
-          echo "##vso[task.setvariable variable=AMLPIPELINEID;isOutput=true]$AMLPIPELINEID"
-      name: 'getpipelineid'
-      displayName: 'Get Pipeline ID'
-  
-    - task: AzureCLI@2
-      inputs:
-        azureSubscription: '$(WORKSPACE_SVC_CONNECTION)'
-        scriptType: bash
-        scriptLocation: inlineScript
-        inlineScript: |
-          echo "Logged subscription:"
-          az account show --query id -o tsv
-
-          echo "Workspace details:"
-          az ml workspace show \
-            --name mlops-AML-WS \
-            --resource-group mlops-RG \
-            --query "{name:name, location:location}"
-
-  - job: "Run_ML_Pipeline"
-    dependsOn: "Get_Pipeline_ID"
-    displayName: "Trigger ML Training Pipeline"
-    timeoutInMinutes: 0
+  - stage: "Trigger_AML_Pipeline"
+    displayName: "Train and evaluate model"
+    condition: succeeded()
     variables:
-      AMLPIPELINE_ID: $[ dependencies.Get_Pipeline_ID.outputs['getpipelineid.AMLPIPELINEID'] ]
-    steps:
-    - task: UsePythonVersion@0
-      inputs:
-        versionSpec: '3.9'
-        addToPath: true
+      BUILD_URI: "$(SYSTEM.COLLECTIONURI)$(SYSTEM.TEAMPROJECT)/_build/results?buildId=$(BUILD.BUILDID)"
+    jobs:
+      - job: "Get_Pipeline_ID"
+        condition: and(succeeded(), eq(coalesce(variables['auto-trigger-training'], 'true'), 'true'))
+        displayName: "Get Pipeline ID for execution"
+        timeoutInMinutes: 0
+        steps:
+          - task: UsePythonVersion@0
+            inputs:
+              versionSpec: "3.9"
+              addToPath: true
 
-    - task: AzureCLI@2
-      inputs:
-        azureSubscription: '$(WORKSPACE_SVC_CONNECTION)'
-        scriptType: bash
-        scriptLocation: inlineScript
-        workingDirectory: $(Build.SourcesDirectory)
-        inlineScript: |
-          set -e
+          - task: AzureCLI@2
+            inputs:
+              azureSubscription: "$(WORKSPACE_SVC_CONNECTION)"
+              scriptType: "bash"
+              scriptLocation: inlineScript
+              workingDirectory: $(Build.SourcesDirectory)
+              inlineScript: |
+                set -e # fail on error
+                python -m pip install --upgrade pip
+                pip install azureml-sdk
+                pip install dotenv
+                export SUBSCRIPTION_ID=$(az account show --query id -o tsv)
+                python -m ml_service.pipelines.run_train_pipeline --output_pipeline_id_file "pipeline_id.txt" --skip_train_execution
+                # Set AMLPIPELINEID variable for next AML Pipeline task in next job
+                AMLPIPELINEID="$(cat pipeline_id.txt)"
+                echo "##vso[task.setvariable variable=AMLPIPELINEID;isOutput=true]$AMLPIPELINEID"
+            name: "getpipelineid"
+            displayName: "Get Pipeline ID"
 
-          python -m pip install --upgrade pip
-          python -m pip install azureml-sdk
-          python -m pip install --upgrade pip
-          pip install dotenv
+          - task: AzureCLI@2
+            inputs:
+              azureSubscription: "$(WORKSPACE_SVC_CONNECTION)"
+              scriptType: bash
+              scriptLocation: inlineScript
+              inlineScript: |
+                echo "Logged subscription:"
+                az account show --query id -o tsv
 
-          export WORKSPACE_NAME=$(WORKSPACE_NAME)
-          export RESOURCE_GROUP=$(RESOURCE_GROUP)
-          export SUBSCRIPTION_ID=$(SUBSCRIPTION_ID)
+                echo "Workspace details:"
+                az ml workspace show \
+                  --name mlops-AML-WS \
+                  --resource-group mlops-RG \
+                  --query "{name:name, location:location}"
 
-          python -m ml_service.pipelines.run_train_pipeline \
-            --pipeline_id $(AMLPIPELINE_ID) \
-            --experiment_name $(EXPERIMENT_NAME) \
-            --model_name $(MODEL_NAME)
-      
-  - job: "Training_Run_Report"
-    dependsOn: "Run_ML_Pipeline"
-    condition: always()
-    displayName: "Publish artifact if new model was registered"
-    container: mlops
-    timeoutInMinutes: 0
-    steps:
-    - template: diabetes_regression-publish-model-artifact-template.yml
+      - job: "Run_ML_Pipeline"
+        dependsOn: "Get_Pipeline_ID"
+        displayName: "Trigger ML Training Pipeline"
+        timeoutInMinutes: 0
+        variables:
+          AMLPIPELINE_ID: $[ dependencies.Get_Pipeline_ID.outputs['getpipelineid.AMLPIPELINEID'] ]
+        steps:
+          - task: UsePythonVersion@0
+            inputs:
+              versionSpec: "3.9"
+              addToPath: true
+
+          - task: AzureCLI@2
+            inputs:
+              azureSubscription: "$(WORKSPACE_SVC_CONNECTION)"
+              scriptType: bash
+              scriptLocation: inlineScript
+              workingDirectory: $(Build.SourcesDirectory)
+              inlineScript: |
+                set -e
+
+                python -m pip install --upgrade pip
+                python -m pip install azureml-sdk
+                python -m pip install --upgrade pip
+                pip install dotenv
+
+                export WORKSPACE_NAME=$(WORKSPACE_NAME)
+                export RESOURCE_GROUP=$(RESOURCE_GROUP)
+                export SUBSCRIPTION_ID=$(SUBSCRIPTION_ID)
+
+                python -m ml_service.pipelines.run_train_pipeline \
+                  --pipeline_id $(AMLPIPELINE_ID) \
+                  --experiment_name $(EXPERIMENT_NAME) \
+                  --model_name $(MODEL_NAME)
+
+      - job: "Training_Run_Report"
+        dependsOn: "Run_ML_Pipeline"
+        condition: always()
+        displayName: "Publish artifact if new model was registered"
+        timeoutInMinutes: 0
+        steps:
+          - template: diabetes_regression-publish-model-artifact-template.yml
