cmt

diff --git a/.pipelines/diabetes_regression-publish-model-artifact-template.yml b/.pipelines/diabetes_regression-publish-model-artifact-template.yml
--- a/.pipelines/diabetes_regression-publish-model-artifact-template.yml
+++ b/.pipelines/diabetes_regression-publish-model-artifact-template.yml
@@ -1,29 +1,41 @@
 # Pipeline template to check if a model was registered for the build and publishes an artifact with the model JSON
 steps:
-- task: AzureCLI@1
-  displayName: 'Install AzureML CLI'
-  inputs:
-    azureSubscription: '$(WORKSPACE_SVC_CONNECTION)'
-    scriptLocation: inlineScript
-    workingDirectory: $(Build.SourcesDirectory)
-    inlineScript: 'az extension add --source https://azurecliext.blob.core.windows.net/release/azure_cli_ml-1.27.0-py3-none-any.whl --yes'
-- task: AzureCLI@1
-  inputs:
-    azureSubscription: '$(WORKSPACE_SVC_CONNECTION)'
-    scriptLocation: inlineScript
-    workingDirectory: $(Build.SourcesDirectory)
-    inlineScript: |
-      set -e # fail on error
+  - task: AzureCLI@2
+    displayName: "Install AzureML CLI"
+    inputs:
+      azureSubscription: "$(WORKSPACE_SVC_CONNECTION)"
+      scriptLocation: inlineScript
+      workingDirectory: $(Build.SourcesDirectory)
+      inlineScript: "az extension add --source https://azurecliext.blob.core.windows.net/release/azure_cli_ml-1.27.0-py3-none-any.whl --yes"
 
-      # Get the model using the build ID tag
-      FOUND_MODEL=$(az ml model list -g $(RESOURCE_GROUP) --workspace-name $(WORKSPACE_NAME) --tag BuildId=$(Build.BuildId) --query '[0]')
-      
-      # If the variable is empty, print and fail
-      [[ -z "$FOUND_MODEL" ]] && { echo "Model was not registered for this run." ; exit 1; }
+  - task: AzureCLI@2
+    inputs:
+      azureSubscription: "$(WORKSPACE_SVC_CONNECTION)"
+      scriptType: "bash"
+      scriptLocation: "inlineScript"
+      inlineScript: |
+        set -e
+        az version
+        az account show
+        displayName: 'Azure Login'
 
-      # Write to a file
-      echo $FOUND_MODEL >model.json
-  name: 'getversion'
-  displayName: "Determine if evaluation succeeded and new model is registered (CLI)"
-- publish: model.json
-  artifact: model
+  - task: AzureCLI@2
+    inputs:
+      azureSubscription: "$(WORKSPACE_SVC_CONNECTION)"
+      scriptLocation: inlineScript
+      workingDirectory: $(Build.SourcesDirectory)
+      inlineScript: |
+        set -e # fail on error
+
+        # Get the model using the build ID tag
+        FOUND_MODEL=$(az ml model list -g $(RESOURCE_GROUP) --workspace-name $(WORKSPACE_NAME) --tag BuildId=$(Build.BuildId) --query '[0]')
+
+        # If the variable is empty, print and fail
+        [[ -z "$FOUND_MODEL" ]] && { echo "Model was not registered for this run." ; exit 1; }
+
+        # Write to a file
+        echo $FOUND_MODEL >model.json
+    name: "getversion"
+    displayName: "Determine if evaluation succeeded and new model is registered (CLI)"
+  - publish: model.json
+    artifact: model
